### ISSUE TITLE
The camera isn't taking prints properly.

### ISSUE THREAD

**Issue by seriousfreezing** [AViewFromTheTop/CameraJavaPort#2]
I don't know if this is a compatibility fault with some mod, but it just takes a screenshot of the blue sky background.
https://paste.atlauncher.com/view/9c8d1c0a-1b81-432b-ad89-3beef8fd9d86

**Comment by AViewFromTheTop** [comment]
If you’re using Iris, that’s the issue. Please report it to them, as I’m using the same technique Mojang uses to take panoramas for cameras.

**Comment by seriousfreezing** [comment]
[Reported.](https://github.com/IrisShaders/Iris/issues/2357)
